name: Regel automatisch bijwerken

on:
  schedule:
    - cron: '0 2 * * 3'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Repository namaken
        uses: actions/checkout@v3

      - name: Tijd bepalen
        run: |
          export TZ=Europe/Amsterdam
          echo "NOW_NL=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i "s/Repository is automatisch bijgewerkt op :.*/Repository is automatisch bijgewerkt op : $NOW_NL/" README.md

      - name: Repository bijwerken
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "README.md bijgewerkt op: $NOW_NL"
          git push
